"""Generate the interface's TypeScript from the engine's own definitions.

The bug this exists to prevent is specific and quiet: the backend renames a
field, the frontend keeps reading the old name, and a card renders with an
empty row. Nothing throws, no test fails, and it is found by a user.

So the wire types are not written twice. They are derived here from the
dataclasses the engine actually emits and from the pack manifests, and
`tests/test_generated_types.py` fails if the checked-in file has drifted. A
change to an engine event is then a build error in the interface rather than a
blank row in production.

    python tools/gen_types.py            # write web/src/types.gen.ts
    python tools/gen_types.py --check    # exit 1 if it would change
"""

from __future__ import annotations

import argparse
import dataclasses
import pathlib
import sys
import typing

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1]))

from core import engine as engine_mod  # noqa: E402
from core.scenario import (  # noqa: E402
    ENGINE_LAYOUTS,
    PACK_LAYOUTS,
    available_scenarios,
    load_scenario,
)

OUTPUT = pathlib.Path(__file__).resolve().parents[1] / "web" / "src" / "types.gen.ts"

# The engine event classes, paired with the SSE names app/main.py sends. Kept
# adjacent so adding an event without naming it is a KeyError here rather than
# an event the interface silently ignores.
EVENTS: list[tuple[str, type]] = [
    ("trace", engine_mod.Trace),
    ("understood_delta", engine_mod.UnderstoodDelta),
    ("understood", engine_mod.Understood),
    ("routed", engine_mod.Routed),
    ("card", engine_mod.CardReady),
    ("reply", engine_mod.ReplyReady),
    ("error", engine_mod.EngineError),
    ("done", engine_mod.Done),
]

# Fields whose Python type is too loose to be useful on the wire, given a
# precise shape by hand. Everything else is derived.
OVERRIDES: dict[tuple[str, str], str] = {
    ("CardReady", "actions"): "ActionButton[]",
    ("EngineError", "actions"): "ActionButton[]",
    ("CardReady", "data"): "CardData",
    # Narrowed from `str` so the renderer's switch is exhaustiveness-checked:
    # adding a layout without implementing it becomes a compile error.
    ("CardReady", "layout"): "Layout",
    ("Done", "usage"): "Usage",
    ("Trace", "detail"): "Record<string, unknown>",
    ("Routed", "arguments"): "Record<string, string | number | boolean>",
}

SCALARS = {str: "string", int: "number", float: "number", bool: "boolean"}


def ts_type(cls_name: str, field: dataclasses.Field) -> str:
    override = OVERRIDES.get((cls_name, field.name))
    if override:
        return override

    annotation = field.type
    if isinstance(annotation, str):  # `from __future__ import annotations`
        annotation = typing.get_type_hints(getattr(engine_mod, cls_name))[field.name]

    if annotation in SCALARS:
        return SCALARS[annotation]

    origin = typing.get_origin(annotation)
    args = typing.get_args(annotation)

    if origin is list:
        inner = args[0] if args else str
        return f"{SCALARS.get(inner, 'unknown')}[]"
    if origin is dict:
        return "Record<string, unknown>"
    if origin is typing.Union or str(origin) == "typing.Union":
        non_none = [a for a in args if a is not type(None)]
        if len(non_none) == 1 and non_none[0] in SCALARS:
            return f"{SCALARS[non_none[0]]} | null"
    return "unknown"


def interface_for(cls: type) -> str:
    lines = [f"export interface {cls.__name__}Payload {{"]
    for field in dataclasses.fields(cls):
        lines.append(f"  {field.name}: {ts_type(cls.__name__, field)};")
    lines.append("}")
    return "\n".join(lines)


def render() -> str:
    packs = available_scenarios()

    parts: list[str] = [
        "// GENERATED by tools/gen_types.py. Do not edit.",
        "//",
        "// Derived from the engine's own dataclasses and the installed scenario",
        "// packs. `pytest tests/test_generated_types.py` fails if this file has",
        "// drifted from them, so a renamed field is a build error here rather than",
        "// an empty row a user finds.",
        "",
        "/** Shapes a card can take. Packs pick one; they never invent one. */",
        "export type PackLayout =\n"
        + "\n".join(f"  | {l!r}".replace("'", '"') for l in PACK_LAYOUTS)
        + ";",
        "",
        "/** Layouts the engine sets itself, on paths every pack has. */",
        "export type EngineLayout =\n"
        + "\n".join(f"  | {l!r}".replace("'", '"') for l in ENGINE_LAYOUTS)
        + ";",
        "",
        "export type Layout = PackLayout | EngineLayout;",
        "",
        "export interface ActionButton {",
        "  id: string;",
        '  label: string;',
        '  variant: "primary" | "secondary" | "danger";',
        "}",
        "",
        "/** Tool output. Keys are declared per card in the manifest, not here:",
        "  * they are pack data, and the renderer reads them through the manifest",
        "  * so an undeclared key is visible rather than silently dropped. */",
        "export type CardData = Record<string, unknown>;",
        "",
        "export interface Usage {",
        "  input_tokens?: number;",
        "  output_tokens?: number;",
        "  cache_read?: number;",
        "  cache_write?: number;",
        "}",
        "",
    ]

    for _, cls in EVENTS:
        parts.append(interface_for(cls))
        parts.append("")

    parts.append("/** The SSE stream, as a discriminated union on the event name. */")
    parts.append("export type EngineEvent =")
    for name, cls in EVENTS:
        parts.append(f'  | {{ name: "{name}"; data: {cls.__name__}Payload }}')
    parts[-1] += ";"
    parts.append("")

    parts.append('export type EventName = EngineEvent["name"];')
    parts.append("")

    parts.extend(
        [
            "export interface ToolSummary {",
            "  name: string;",
            "  description: string;",
            "  card: string;",
            "}",
            "",
            "export interface CardSpec {",
            "  layout: Layout;",
            "  fields: string[];",
            "  optional_fields: string[];",
            "}",
            "",
            "export interface DemoSummary {",
            "  id: string;",
            "  label: string;",
            "  utterance: string;",
            "}",
            "",
            "export interface ScenarioManifest {",
            "  id: string;",
            "  name: string;",
            "  languages: string[];",
            "  default_language: string;",
            "  tools: ToolSummary[];",
            "  cards: Record<string, CardSpec>;",
            "  demos: DemoSummary[];",
            "}",
            "",
        ]
    )

    # Every field name any installed pack can put on a card. The renderer uses
    # this to tell "a field this pack does not have" from "a field name that
    # exists nowhere", which is the typo case.
    known: dict[str, set[str]] = {}
    for pack_id in packs:
        scenario = load_scenario(pack_id)
        fields: set[str] = set()
        for card in scenario.spec.cards.values():
            fields |= set(card.fields) | set(card.optional_fields)
        known[pack_id] = fields

    parts.append("/** Card fields declared by each installed pack, at generation time. */")
    parts.append("export const PACK_FIELDS = {")
    for pack_id in sorted(known):
        rendered = ", ".join(f'"{f}"' for f in sorted(known[pack_id]))
        parts.append(f"  {pack_id}: [{rendered}],")
    parts.append("} as const;")
    parts.append("")
    parts.append("export type KnownPack = keyof typeof PACK_FIELDS;")
    parts.append("")

    return "\n".join(parts)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="exit 1 if the file would change")
    args = parser.parse_args()

    generated = render()

    if args.check:
        if not OUTPUT.is_file():
            print(f"{OUTPUT} does not exist; run `python tools/gen_types.py`", file=sys.stderr)
            return 1
        current = OUTPUT.read_text(encoding="utf-8")
        if current != generated:
            print(
                f"{OUTPUT} is out of date with the engine.\n"
                f"Run `python tools/gen_types.py` and commit the result.",
                file=sys.stderr,
            )
            return 1
        print(f"{OUTPUT} is up to date")
        return 0

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(generated, encoding="utf-8")
    print(f"wrote {OUTPUT} ({len(generated.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
