// GENERATED by tools/gen_types.py. Do not edit.
//
// Derived from the engine's own dataclasses and the installed scenario
// packs. `pytest tests/test_generated_types.py` fails if this file has
// drifted from them, so a renamed field is a build error here rather than
// an empty row a user finds.

/** Shapes a card can take. Packs pick one; they never invent one. */
export type PackLayout =
  | "pass"
  | "status"
  | "plan"
  | "range"
  | "steps"
  | "detail";

/** Layouts the engine sets itself, on paths every pack has. */
export type EngineLayout =
  | "urgent"
  | "notice";

export type Layout = PackLayout | EngineLayout;

export interface ActionButton {
  id: string;
  label: string;
  variant: "primary" | "secondary" | "danger";
}

/** Tool output. Keys are declared per card in the manifest, not here:
  * they are pack data, and the renderer reads them through the manifest
  * so an undeclared key is visible rather than silently dropped. */
export type CardData = Record<string, unknown>;

export interface Usage {
  input_tokens?: number;
  output_tokens?: number;
  cache_read?: number;
  cache_write?: number;
}

export interface TracePayload {
  stage: string;
  t_ms: number;
  detail: Record<string, unknown>;
}

export interface UnderstoodDeltaPayload {
  text: string;
}

export interface UnderstoodPayload {
  text: string;
  language: string;
}

export interface RoutedPayload {
  action: string;
  arguments: Record<string, string | number | boolean>;
}

export interface CardReadyPayload {
  card: string;
  layout: Layout;
  data: CardData;
  actions: ActionButton[];
}

export interface ReplyReadyPayload {
  text: string;
  sources: string[];
}

export interface EngineErrorPayload {
  kind: string;
  message: string;
  actions: ActionButton[];
}

export interface DonePayload {
  usage: Usage;
}

/** The SSE stream, as a discriminated union on the event name. */
export type EngineEvent =
  | { name: "trace"; data: TracePayload }
  | { name: "understood_delta"; data: UnderstoodDeltaPayload }
  | { name: "understood"; data: UnderstoodPayload }
  | { name: "routed"; data: RoutedPayload }
  | { name: "card"; data: CardReadyPayload }
  | { name: "reply"; data: ReplyReadyPayload }
  | { name: "error"; data: EngineErrorPayload }
  | { name: "done"; data: DonePayload };

export type EventName = EngineEvent["name"];

export interface ToolSummary {
  name: string;
  description: string;
  card: string;
}

export interface CardSpec {
  layout: Layout;
  fields: string[];
  optional_fields: string[];
}

export interface DemoSummary {
  id: string;
  label: string;
  utterance: string;
}

export interface ScenarioManifest {
  id: string;
  name: string;
  languages: string[];
  default_language: string;
  tools: ToolSummary[];
  cards: Record<string, CardSpec>;
  demos: DemoSummary[];
}

/** Card fields declared by each installed pack, at generation time. */
export const PACK_FIELDS = {
  airport: ["backup_departs", "backup_flight", "barcode", "belt", "boarding_group", "boarding_time", "cabin", "departs", "destination", "eligibility", "estimated", "flight", "gate", "hall", "held_seat", "hours", "inbound", "location", "lounge", "minutes_to_connect", "onward", "onward_gate", "passenger", "previous_gate", "ready_at", "reason", "risk", "route", "scheduled", "seat", "sequence", "status", "steps", "summary", "title", "voucher_code", "voucher_note", "voucher_value", "walk_minutes"],
  frontdesk: ["address", "area", "arrival_note", "coverage", "currency", "customer", "diagnostic_fee", "equipment", "eta_minutes", "expires", "hours", "includes", "issue", "job_ref", "last_visit", "note", "plan", "priority", "range_high", "range_low", "service", "status", "summary", "technician", "title", "vehicle", "window"],
} as const;

export type KnownPack = keyof typeof PACK_FIELDS;
